**TO - DO - Task**

**4.1	Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

Complete the following Tasks:
1.	Initialize an empty array with size 2X2.
2.	Initialize an all one array with size 4X2.
3.	Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4.	Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5.	Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6.	For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}



In [1]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array (2x2):")
print(empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-ones array (4x2):")
print(ones_array)

# 3. Return a new array of given shape and type, filled with fill value (using np.full)
shape = (3, 3)
fill_value = 7
full_array = np.full(shape, fill_value)
print("\nArray filled with value 7 (3x3):")
print(full_array)

# 4. Return a new array of zeros with same shape and type as a given array (using np.zeros_like)
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros array with the same shape as reference array:")
print(zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array (using np.ones_like)
ones_like_array = np.ones_like(reference_array)
print("\nOnes array with the same shape as reference array:")
print(ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy array from list [1, 2, 3, 4]:")
print(numpy_array)


Empty array (2x2):
[[6.79159354e-310 0.00000000e+000]
 [4.94065646e-324             nan]]

All-ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array with the same shape as reference array:
[[0 0 0]
 [0 0 0]]

Ones array with the same shape as reference array:
[[1 1 1]
 [1 1 1]]

Numpy array from list [1, 2, 3, 4]:
[1 2 3 4]


**4.1.1	Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:
1.	Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2.	Create a 3X3 matrix with values ranging from 0 to 8.

{Hint:look for np.reshape()}
3.	Create a 3X3 identity matrix.{Hint:np.eye()}
4.	Create a random array of size 30 and find the mean of the array.

{Hint:check for np.random.random() and array.mean() function}
5.	Create a 10X10 array with random values and find the minimum and maximum values.
6.	Create a zero array of size 10 and replace 5th element with 1.
7.	Reverse an array arr = [1,2,0,0,4,0].
8.	Create a 2d array with 1 on border and 0 inside.
9.	Create a 8X8 matrix and fill it with a checkerboard pattern.


In [2]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array with values from 10 to 49:")
print(array_10_to_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:")
print(matrix_0_to_8)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 identity matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30 and its mean:")
print(random_array)
print("Mean:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n10x10 random array, min and max values:")
print(random_matrix)
print("Min:", min_value, "Max:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array of size 10 with 5th element replaced by 1:")
print(zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nReversed array:")
print(reversed_array)

# 8. Create a 2D array with 1 on border and 0 inside
bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:")
print(bordered_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[::2, 1::2] = 1
checkerboard_matrix[1::2, ::2] = 1
print("\n8x8 checkerboard matrix:")
print(checkerboard_matrix)


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30 and its mean:
[0.87391409 0.19738876 0.35422892 0.77593814 0.52472904 0.1715226
 0.99676484 0.62587594 0.41242154 0.40373411 0.48030404 0.07028496
 0.62446433 0.25631703 0.62812067 0.85963413 0.80531383 0.26355153
 0.72168135 0.84329095 0.88258617 0.60838523 0.30103561 0.63437417
 0.05760354 0.53401218 0.20013306 0.61793982 0.09674887 0.99617492]
Mean: 0.5272824789935423

10x10 random array, min and max values:
[[0.18862434 0.15985314 0.35577507 0.02701121 0.01975379 0.70080788
  0.22361745 0.76512776 0.55162236 0.60318653]
 [0.54305255 0.33127706 0.52821119 0.92843895 0.69414646 0.01659625
  0.55676453 0.71537442 0.61926187 0.4704483 ]
 [0.35169999 0.25914615 0.67882434 0.09940674 0.14

**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:
1.	Add the two array.
2.	Subtract the two array.
3.	Multiply the array with any integers of your choice.
4.	Find the square of each element of the array.
5.	Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6.	Concatenate x(and)y along row and Concatenate v(and)w along column.

{Hint:try np.concatenate() or np.vstack() functions.
7.	Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [3]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
array_sum = x + y
print("Sum of x and y:")
print(array_sum)

# 2. Subtract the two arrays
array_diff = x - y
print("\nDifference of x and y:")
print(array_diff)

# 3. Multiply the array x with any integer (choosing 3)
array_multiplied = x * 3
print("\nArray x multiplied by 3:")
print(array_multiplied)

# 4. Find the square of each element of the array x
array_squared = x ** 2
print("\nSquare of each element in x:")
print(array_squared)

# 5. Find the dot product
dot_v_w = np.dot(v, w)  # Dot product between v and w
dot_x_v = np.dot(x, v)  # Dot product between x and v
dot_x_y = np.dot(x, y)  # Dot product between x and y
print("\nDot product of v and w:", dot_v_w)
print("Dot product of x and v:")
print(dot_x_v)
print("Dot product of x and y:")
print(dot_x_y)

# 6. Concatenate x and y along rows and v and w along columns
concat_x_y_row = np.concatenate((x, y), axis=0)
concat_v_w_column = np.vstack((v, w))  # Or np.column_stack((v, w))
print("\nConcatenation of x and y along rows:")
print(concat_x_y_row)
print("Concatenation of v and w along columns:")
print(concat_v_w_column)

# 7. Concatenate x and v
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v along rows:")
    print(concat_x_v)
except ValueError as e:
    print("\nError in concatenating x and v:")
    print(e)
    print("Explanation: x has shape (2, 2), and v has shape (2,). "
          "Concatenation requires matching dimensions, and here, "
          "v must be reshaped to (1, 2) to match x along the row axis.")


Sum of x and y:
[[ 6  8]
 [10 13]]

Difference of x and y:
[[-4 -4]
 [-4 -3]]

Array x multiplied by 3:
[[ 3  6]
 [ 9 15]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
[[ 9 10]
 [11 12]]

Error in concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x has shape (2, 2), and v has shape (2,). Concatenation requires matching dimensions, and here, v must be reshaped to (1, 2) to match x along the row axis.


**Problem - 4: Matrix Operations: • For the following arrays:**

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:
1.	Prove A.A−1 = I.
2.	Prove AB ̸= BA.
3.	Prove (AB)T = BTAT.

•	Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1 x − y + 2z = −3 3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

•	Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}


In [4]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)
result_1 = np.dot(A, A_inv)
print("Prove A * A⁻¹ = I:")
print(result_1)  # Should be the identity matrix

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nProve AB ≠ BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T_A_T = np.dot(B.T, A.T)
print("\nProve (AB)^T = B^T * A^T:")
print("(AB)^T:")
print(AB_T)
print("B^T * A^T:")
print(B_T_A_T)
print("Are (AB)^T and B^T * A^T equal?", np.array_equal(AB_T, B_T_A_T))


Prove A * A⁻¹ = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Prove AB ≠ BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Are AB and BA equal? False

Prove (AB)^T = B^T * A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal? True


In [5]:
# Define the coefficient matrix A and the constants matrix B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve using np.linalg.inv
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\nSolution using np.linalg.inv:")
print("X = [x, y, z]:", X)

# Verify solution using np.linalg.solve
X_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:")
print("X = [x, y, z]:", X_solve)

# Verify that both methods give the same result
print("\nAre the two solutions equal?", np.allclose(X, X_solve))



Solution using np.linalg.inv:
X = [x, y, z]: [ 2.  1. -2.]

Solution using np.linalg.solve:
X = [x, y, z]: [ 2.  1. -2.]

Are the two solutions equal? True


4.2	Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
•	Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
2. Element-wise Multiplication
•	Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
3. Dot Product
•	Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
4. Matrix Multiplication
•	Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
•	Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


In [ ]:
import numpy as np
import time

# Helper function to measure execution time
def measure_time(func, *args, **kwargs):
    start = time.time()
    result = func(*args, **kwargs)
    end = time.time()
    return result, end - start

# 1. Element-wise Addition
size = 1_000_000

# Using Python Lists
list1 = list(range(size))
list2 = list(range(size))
_, time_list_add = measure_time(lambda: [list1[i] + list2[i] for i in range(size)])

# Using NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)
_, time_numpy_add = measure_time(lambda: array1 + array2)

print(f"Element-wise addition time (Python lists): {time_list_add:.4f} seconds")
print(f"Element-wise addition time (NumPy arrays): {time_numpy_add:.4f} seconds")

# 2. Element-wise Multiplication
# Using Python Lists
_, time_list_mult = measure_time(lambda: [list1[i] * list2[i] for i in range(size)])

# Using NumPy Arrays
_, time_numpy_mult = measure_time(lambda: array1 * array2)

print(f"\nElement-wise multiplication time (Python lists): {time_list_mult:.4f} seconds")
print(f"Element-wise multiplication time (NumPy arrays): {time_numpy_mult:.4f} seconds")

# 3. Dot Product
# Using Python Lists
_, time_list_dot = measure_time(lambda: sum(list1[i] * list2[i] for i in range(size)))

# Using NumPy Arrays
_, time_numpy_dot = measure_time(lambda: np.dot(array1, array2))

print(f"\nDot product time (Python lists): {time_list_dot:.4f} seconds")
print(f"Dot product time (NumPy arrays): {time_numpy_dot:.4f} seconds")

# 4. Matrix Multiplication
matrix_size = 1000

# Using Python Lists
matrix1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
_, time_list_matrix_mult = measure_time(
    lambda: [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
)

# Using NumPy Arrays
np_matrix1 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)
_, time_numpy_matrix_mult = measure_time(lambda: np.dot(np_matrix1, np_matrix2))

print(f"\nMatrix multiplication time (Python lists): {time_list_matrix_mult:.4f} seconds")
print(f"Matrix multiplication time (NumPy arrays): {time_numpy_matrix_mult:.4f} seconds")


Element-wise addition time (Python lists): 0.1804 seconds
Element-wise addition time (NumPy arrays): 0.0040 seconds

Element-wise multiplication time (Python lists): 0.2041 seconds
Element-wise multiplication time (NumPy arrays): 0.0056 seconds

Dot product time (Python lists): 0.3058 seconds
Dot product time (NumPy arrays): 0.0018 seconds
